# SumiNami - Fuzzel config (kanagawa)

[main]
font=JetBrainsMono Nerd Font:size=11:weight=bold
prompt=❯
icon-theme=Papirus-Dark
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
# Kanagawa palette
background=16161Dee
text=DCD7BAff
prompt=D27E99ff
placeholder=54546Dff
input=DCD7BAff
match=D27E99ff
selection=D27E99ff
selection-text=16161Dff
selection-match=16161Dff
border=363646ff

[border]
width=1
radius=8

[dmenu]
exit-immediately-if-empty=no
