# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Kitty opacity changes
# windowrulev2 = opacity 0.91,class:^(kitty)$
# windowrulev2 = opacity 0.94,class:^(kitty)$,focus:1

# Firefox opacity changes (same as kitty)
# windowrulev2 = opacity 0.91,class:^(firefox)$
# windowrulev2 = opacity 0.94,class:^(firefox)$,focus:1

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0