#!/bin/bash
# Application launcher - reads command from suminami.conf

CONFIG_FILE="$HOME/.config/waybar/suminami.conf"

# Get launcher command from config, default to wofi
launcher_cmd="wofi --show drun"
if [ -f "$CONFIG_FILE" ]; then
    configured=$(grep "^launcher_command=" "$CONFIG_FILE" | cut -d'=' -f2-)
    if [ -n "$configured" ]; then
        # Expand ~ and $HOME in the command
        configured="${configured/#\~/$HOME}"
        configured="${configured//\$HOME/$HOME}"
        launcher_cmd="$configured"
    fi
fi

# Execute the launcher
exec $launcher_cmd
