#!/bin/bash
# Suminami Theme Generator
# Reads the current theme and generates styles for all components

SUMINAMI_DIR="$HOME/.config/suminami"
THEMES_DIR="$SUMINAMI_DIR/themes"
CURRENT_THEME=$(cat "$THEMES_DIR/current" 2>/dev/null || echo "kanagawa")

# Source the theme
THEME_FILE="$THEMES_DIR/$CURRENT_THEME.sh"
if [ ! -f "$THEME_FILE" ]; then
    echo "Theme not found: $CURRENT_THEME"
    exit 1
fi
source "$THEME_FILE"

echo "Generating styles for theme: $THEME_NAME ($THEME_TYPE)"

# Generate Rofi theme
generate_rofi() {
    mkdir -p "$HOME/.config/rofi"

    # Convert hex to rgba for 96% opacity background
    # Extract RGB components from BG_PRIMARY (e.g., #16161D -> 22, 22, 29)
    local bg_hex="${BG_PRIMARY#\#}"
    local r=$((16#${bg_hex:0:2}))
    local g=$((16#${bg_hex:2:2}))
    local b=$((16#${bg_hex:4:2}))

    cat > "$HOME/.config/rofi/suminami.rasi" << EOF
/* SumiNami Rofi Theme - $THEME_NAME */
/* Auto-generated by generate-theme.sh */

* {
    bg:           rgba($r, $g, $b, 96%);
    bg-alt:       $BG_TERTIARY;
    fg:           $FG_PRIMARY;
    fg-alt:       $FG_MUTED;
    accent:       $ACCENT_PRIMARY;
    urgent:       $ACCENT_ERROR;
    border-grey:  #dddddd;

    background-color: transparent;
    text-color: @fg;
    margin: 0;
    padding: 0;
    spacing: 0;
}

window {
    background-color: @bg;
    border: 1px;
    border-color: @border-grey;
    border-radius: 0;
    width: 450px;
    padding: 12px;
}

mainbox {
    children: [inputbar, listview];
    spacing: 8px;
}

inputbar {
    background-color: @bg-alt;
    border: 1px;
    border-color: @border-grey;
    border-radius: 0;
    padding: 8px 12px;
    children: [prompt, entry];
    spacing: 8px;
}

prompt {
    text-color: @accent;
}

entry {
    placeholder: "Search...";
    placeholder-color: @fg-alt;
}

listview {
    lines: 8;
    columns: 1;
    fixed-height: false;
    scrollbar: false;
    spacing: 2px;
}

element {
    padding: 8px 14px;
    border-radius: 0;
    spacing: 8px;
}

element normal.normal {
    background-color: transparent;
}

element normal.urgent {
    text-color: @urgent;
}

element normal.active {
    text-color: @accent;
}

element selected.normal {
    background-color: rgba(${r}, ${g}, ${b}, 50%);
    text-color: @accent;
}

element selected.urgent {
    background-color: @urgent;
    text-color: @bg;
}

element selected.active {
    background-color: @accent;
    text-color: @bg;
}

element-icon {
    size: 24px;
}

element-text {
    text-color: inherit;
    vertical-align: 0.5;
}
EOF
    echo "  ✓ Rofi theme generated"
}

# Generate Waybar colors
generate_waybar_colors() {
    # Use raw palette colors if available, otherwise fallback to semantic
    local sumi_ink1="${RAW_SUMI_INK1:-$BG_SECONDARY}"
    local sumi_ink2="${RAW_SUMI_INK2:-$BG_SECONDARY}"
    local sumi_ink3="${RAW_SUMI_INK3:-$BG_SECONDARY}"
    local sumi_ink5="${RAW_SUMI_INK5:-$BORDER_COLOR}"
    local sumi_ink6="${RAW_SUMI_INK6:-$FG_MUTED}"
    local fuji_gray="${RAW_FUJI_GRAY:-$FG_MUTED}"
    local sakura_pink="${RAW_SAKURA_PINK:-$ACCENT_PRIMARY}"
    local oni_violet="${RAW_ONI_VIOLET:-$MODULE_MEMORY}"
    local crystal_blue="${RAW_CRYSTAL_BLUE:-$ACCENT_SECONDARY}"
    local spring_blue="${RAW_SPRING_BLUE:-$MODULE_VOLUME}"
    local light_blue="${RAW_LIGHT_BLUE:-$MODULE_NETWORK}"
    local spring_green="${RAW_SPRING_GREEN:-$ACCENT_TERTIARY}"
    local carp_yellow="${RAW_CARP_YELLOW:-$MODULE_BRIGHTNESS}"
    local wave_red="${RAW_WAVE_RED:-$ACCENT_ERROR}"
    local peach_red="${RAW_PEACH_RED:-$MODULE_TEMP}"
    local surimi_orange="${RAW_SURIMI_ORANGE:-$ACCENT_WARNING}"
    local wave_aqua="${RAW_WAVE_AQUA:-$MODULE_NETWORK}"
    local katana_gray="${RAW_KATANA_GRAY:-$FG_MUTED}"
    local dragon_blue="${RAW_DRAGON_BLUE:-$MODULE_BLUETOOTH}"

    # Module-specific overrides
    local module_muted="${RAW_MODULE_MUTED:-$fuji_gray}"
    local module_system="${RAW_MODULE_SYSTEM:-$ACCENT_TERTIARY}"
    local module_weather="${RAW_MODULE_WEATHER:-$light_blue}"

    cat > "$HOME/.config/waybar/colors.css" << EOF
/* SumiNami - Waybar colors ($THEME_NAME) */
/* Auto-generated by generate-theme.sh */

/* Background shades */
@define-color sumiInk0 $BG_PRIMARY;
@define-color sumiInk1 $sumi_ink1;
@define-color sumiInk2 $sumi_ink2;
@define-color sumiInk3 $sumi_ink3;
@define-color sumiInk4 $BG_TERTIARY;
@define-color sumiInk5 $sumi_ink5;
@define-color sumiInk6 $sumi_ink6;

/* Foreground */
@define-color fujiWhite $FG_PRIMARY;
@define-color fujiGray $fuji_gray;
@define-color oldWhite $FG_SECONDARY;

/* Accent colors */
@define-color sakuraPink $sakura_pink;
@define-color oniViolet $oni_violet;
@define-color crystalBlue $crystal_blue;
@define-color springBlue $spring_blue;
@define-color lightBlue $light_blue;

/* Semantic colors */
@define-color springGreen $spring_green;
@define-color carpYellow $carp_yellow;
@define-color waveRed $wave_red;
@define-color peachRed $peach_red;
@define-color surimiOrange $surimi_orange;

/* Extra */
@define-color waveAqua $wave_aqua;
@define-color katanaGray $katana_gray;
@define-color dragonBlue $dragon_blue;

/* Semantic module colors */
@define-color module-clock $MODULE_CLOCK;
@define-color module-launcher $MODULE_LAUNCHER;
@define-color module-workspace-active $MODULE_WORKSPACE_ACTIVE;
@define-color module-system $module_system;
@define-color module-media $MODULE_MEDIA;
@define-color module-weather $module_weather;
@define-color module-network $MODULE_NETWORK;
@define-color module-audio $MODULE_VOLUME;
@define-color module-bluetooth $MODULE_BLUETOOTH;
@define-color module-muted $module_muted;
@define-color state-warning $ACCENT_WARNING;
@define-color state-critical $ACCENT_ERROR;
EOF
    echo "  ✓ Waybar colors generated"
}

# Generate waybar script colors.sh
generate_waybar_script_colors() {
    mkdir -p "$HOME/.config/waybar/scripts"
    cat > "$HOME/.config/waybar/scripts/colors.sh" << EOF
#!/bin/bash
# SumiNami - Script colors ($THEME_NAME)
# Auto-generated by generate-theme.sh

# Theme info
THEME_NAME="$THEME_NAME"
THEME_IS_LIGHT=$( [ "$THEME_TYPE" = "light" ] && echo "true" || echo "false" )

# Colors for scripts (pango markup)
COLOR_ACCENT="$ACCENT_PRIMARY"
COLOR_FG="$FG_PRIMARY"
COLOR_FG_ALT="$FG_SECONDARY"
COLOR_MUTED="$FG_MUTED"

# Semantic colors used by scripts
COLOR_SYSTEM="$ACCENT_TERTIARY"
COLOR_SUCCESS="$ACCENT_TERTIARY"
COLOR_WARNING="$ACCENT_WARNING"
COLOR_ERROR="$ACCENT_ERROR"
COLOR_CRITICAL="$ACCENT_ERROR"

# Module-specific colors
COLOR_AUDIO="$MODULE_VOLUME"
COLOR_HIGHLIGHT="$ACCENT_SECONDARY"
COLOR_NETWORK="$MODULE_NETWORK"
COLOR_BLUETOOTH="$MODULE_BLUETOOTH"
COLOR_MEDIA="$MODULE_MEDIA"
EOF
    chmod +x "$HOME/.config/waybar/scripts/colors.sh"
    echo "  ✓ Waybar script colors generated"
}

# Generate Dunst colors
generate_dunst() {
    local dunstrc="$HOME/.config/dunst/dunstrc"
    [ ! -f "$dunstrc" ] && return

    # Convert hex to hex with alpha (f5 = ~96% opacity)
    local bg_alpha="${BG_PRIMARY}f5"

    # Update urgency_low
    sed -i '/^\[urgency_low\]/,/^\[/ {
        s/background = .*/background = "'"$bg_alpha"'"/
        s/foreground = .*/foreground = "'"$FG_PRIMARY"'"/
        s/frame_color = .*/frame_color = "#dddddd"/
    }' "$dunstrc"

    # Update urgency_normal
    sed -i '/^\[urgency_normal\]/,/^\[/ {
        s/background = .*/background = "'"$bg_alpha"'"/
        s/foreground = .*/foreground = "'"$FG_PRIMARY"'"/
        s/frame_color = .*/frame_color = "#dddddd"/
        s/highlight = .*/highlight = "'"$ACCENT_PRIMARY"'"/
    }' "$dunstrc"

    # Update urgency_critical
    sed -i '/^\[urgency_critical\]/,/^\[/ {
        s/background = .*/background = "'"$bg_alpha"'"/
        s/foreground = .*/foreground = "'"$FG_PRIMARY"'"/
        s/frame_color = .*/frame_color = "'"$ACCENT_ERROR"'"/
        s/highlight = .*/highlight = "'"$ACCENT_ERROR"'"/
    }' "$dunstrc"

    echo "  ✓ Dunst colors generated"
}

# Generate GTK theme settings
generate_gtk() {
    local gtk_theme=""
    local icon_theme="Papirus-Dark"

    # Map SumiNami theme to GTK theme
    case "$CURRENT_THEME" in
        kanagawa)
            gtk_theme="Kanagawa-Dark"
            ;;
        kanagawa-dragon)
            gtk_theme="Kanagawa-Purple-Dark"
            ;;
        kanagawa-lotus)
            gtk_theme="Kanagawa-Light"
            icon_theme="Papirus-Light"
            ;;
        kanagawa-blossom)
            gtk_theme="Kanagawa-Pink-Dark"
            ;;
        catppuccin-mocha)
            gtk_theme="catppuccin-mocha-blue-standard+default"
            ;;
        catppuccin-macchiato)
            gtk_theme="catppuccin-macchiato-blue-standard+default"
            ;;
        catppuccin-frappe)
            gtk_theme="catppuccin-frappe-blue-standard+default"
            ;;
        catppuccin-latte)
            gtk_theme="catppuccin-latte-blue-standard+default"
            icon_theme="Papirus-Light"
            ;;
        gruvbox-dark)
            gtk_theme="Gruvbox-Dark"
            ;;
        *)
            gtk_theme="Kanagawa-Dark"
            ;;
    esac

    # Set GTK theme via gsettings (for GNOME/GTK apps)
    if command -v gsettings &> /dev/null; then
        gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme" 2>/dev/null || true
        gsettings set org.gnome.desktop.interface icon-theme "$icon_theme" 2>/dev/null || true

        # Set color scheme for GTK4
        if [ "$THEME_TYPE" = "light" ]; then
            gsettings set org.gnome.desktop.interface color-scheme "prefer-light" 2>/dev/null || true
        else
            gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" 2>/dev/null || true
        fi
    fi

    # Also write to GTK settings files for non-GNOME environments
    mkdir -p "$HOME/.config/gtk-3.0"
    mkdir -p "$HOME/.config/gtk-4.0"

    cat > "$HOME/.config/gtk-3.0/settings.ini" << EOF
[Settings]
gtk-theme-name=$gtk_theme
gtk-icon-theme-name=$icon_theme
gtk-font-name=JetBrainsMono Nerd Font 10
gtk-cursor-theme-name=Bibata-Modern-Classic
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=$( [ "$THEME_TYPE" = "dark" ] && echo "true" || echo "false" )
EOF

    cat > "$HOME/.config/gtk-4.0/settings.ini" << EOF
[Settings]
gtk-theme-name=$gtk_theme
gtk-icon-theme-name=$icon_theme
gtk-font-name=JetBrainsMono Nerd Font 10
gtk-cursor-theme-name=Bibata-Modern-Classic
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=$( [ "$THEME_TYPE" = "dark" ] && echo "true" || echo "false" )
EOF

    echo "  ✓ GTK theme set to $gtk_theme"
}

# Run all generators
generate_rofi
generate_waybar_colors
generate_waybar_script_colors
generate_dunst
generate_gtk

echo "Theme generation complete!"
